### PR TITLE
Using context variable GIANTSWARM_LOGIN_NAME to simplify swarm up

### PR DESCRIPTION
**Pull request by luebken**
RFR @marians @puja108

### CODE REVIEW

**Comment by luebken** [comment]
This would especially simplify the quickstart: https://docs.giantswarm.io/ see https://github.com/giantswarm/docs/blob/master/swarmdocs/layouts/index.html#L123

**Comment by marians** [comment]
I like the simplification. However, this change not only breaks the quickstart on our docs start page, but also two of our testbot tests:

https://github.com/giantswarm/testbot/blob/master/testscripts/helloworldscript-leaseweb.yaml#L38
https://github.com/giantswarm/testbot/blob/master/testscripts/helloworldscript.yaml#L41

There we benefit from the fact that the domain can be randomized completely, to avoid using any previously existing routing layer entries.

Of course we could provide an entirely different test service for testbot. But I kind of like the fact that testbot tests exactly the same service our users are pushed to do as a first step.

**Comment by luebken** [comment]
Thanks for pointing that out. 

In my opinion the change would be minor and it does't have to be an entirely different test service. In fact we could just create `test-bot` branch in this repo and clone that in the test-bot scripts.

**Comment by puja108** [comment]
I also like the simplification, and it shows the use of variables earl on. I would rather let our helloworld be driven by what is good for the user than by requirements of testbot. @luebken's suggestion with the branch should be sufficient. AFAIK we're not building in the test-bot scripts anyway, but using a pre-built image from DockerHub. It would also pull apart our actual helloworld usage vs. testbot usage of our helloworld (see Slack yesterday)

**Comment by luebken** [comment]
Image would stay the same.

**Comment by puja108** [comment]
true, didn't think about it ;)

**Comment by zeisss** [comment]
can we merge this?

**Comment by puja108** [comment]
not sure if the issues @marians mentioned still persist, if not, then merge

**Comment by marians** [comment]
Lo longer relevant

**Pull request closed without merging**
